image:
  node:10.15.0-alpine

stages:
  - test

test:
  stage: test
  script:
    - npm install --registry="http://npm.repos.beibei.com.cn/"
    - npm run eslint
    - npm run test
    - npm run test:coverage
    - npm run test:report
  except:
      - /^(doc|dev)/
